Nelder-Mid Library: src/Checking_func.cpp File Reference
Checking_func.cpp File Reference
#include <string>
#include <unordered_set>
#include "Internal_func.h"
Functions
bool check_chars (const string &function_str)
string check_correct (const char *function_str_c)
Function Documentation
check_chars()
bool check_chars (const string & function_str)
Referenced by check_correct().
check_correct()
string check_correct (const char * function_str_c)
References check_chars().
Referenced by create_tree().