Nelder-Mid Library: include/Internal_func.h File Reference
Internal_func.h File Reference
#include <map>
#include <string>
#include <vector>
#include "Classes.h"
Classes
class Operators
Functions
bool is_operator (char c)
bool is_operator (const string &c)
ExpressionTree * rpn_expr_to_tree (vector< string > &rpn_expression)
vector< string > infen_expr_to_rpn (const string &infenex_expr)
bool check_chars (const string &function_str)
string check_correct (const char *function_str_c)
Function Documentation
check_chars()
bool check_chars (const string & function_str)
Referenced by check_correct().
check_correct()
string check_correct (const char * function_str_c)
References check_chars().
Referenced by create_tree().
infen_expr_to_rpn()
vector< string > infen_expr_to_rpn (const string & infenex_expr)
References is_operator(), and Operators::precedence.
Referenced by create_tree().
is_operator() [1/2]
bool is_operator (char c)
References Operators::precedence.
Referenced by infen_expr_to_rpn(), and rpn_expr_to_tree().
is_operator() [2/2]
bool is_operator (const string & c)
References Operators::precedence.
rpn_expr_to_tree()
ExpressionTree * rpn_expr_to_tree (vector< string > & rpn_expression)
References is_operator().
Referenced by create_tree().