Nelder-Mid Library: Functions
Functions
Основные функции для работы с деревьями выражений
Functions
ExpressionTree * create_tree (const char *function_str)
Создает дерево выражений из строки
double evaluate_tree (ExpressionTree *trее)
Вычисляет значение дерева выражений
void create_solution (const int num_variable, const double *variables)
Инициализирует переменные в Solution.
Detailed Description
Основные функции для работы с деревьями выражений
Function Documentation
create_solution()
void create_solution (const int num_variable, const double * variables)
#include <include/NelderMead.h>
Инициализирует переменные в Solution.
Parameters
num_variable Количество переменных
variables Массив значений (x1, x2, ..., xn)
Создает переменные с именами "x1", "x2" и т.д.
Note
Перезаписывает существующие переменные с такими именами
References Solution::set().
create_tree()
ExpressionTree * create_tree (const char * function_str_c)
#include <include/NelderMead.h>
Создает дерево выражений из строки
Parameters
function_str Строка с математическим выражением (например, "x1 + sin(x2)")
Returns
Указатель на созданное дерево выражений или nullptr при ошибке
Warning
Строка должна содержать корректное математическое выражение
Parameters
function_str_c C-строка с выражением
Returns
Указатель на дерево или nullptr при ошибке
Этапы обработки:
Проверка корректности строки
Преобразование в обратную польскую нотацию
Построение дерева выражений
See also
check_correct(), infen_expr_to_rpn(), rpn_expr_to_tree()
References check_correct(), infen_expr_to_rpn(), and rpn_expr_to_tree().
evaluate_tree()
double evaluate_tree (ExpressionTree * tree)
#include <include/NelderMead.h>
Вычисляет значение дерева выражений
Parameters
tree Указатель на валидное дерево выражений
Returns
Результат вычисления
Parameters
tree Указатель на дерево выражений
Returns
Результат вычисления
Note
Перед вызовом убедитесь, что все переменные установлены через Solution
References ExpressionTree::evaluate().